# Generated by Django 5.2.5 on 2025-08-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISMDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_id', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('merchandise_code', models.CharField(max_length=32)),
                ('selling_units', models.IntegerField()),
                ('actual_sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_quantity', models.IntegerField()),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_count', models.IntegerField()),
                ('promotion_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promotion_count', models.IntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_count', models.IntegerField()),
                ('transaction_count', models.IntegerField()),
            ],
        ),
    ]
