# Generated by Django 5.2.5 on 2025-08-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ismdetail',
            name='site_id',
            field=models.CharField(default=62182, max_length=8),
            preserve_default=False,
        ),
    ]
