# Generated by Django 5.2.5 on 2025-08-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0002_ismdetail_site_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ismdetail',
            unique_together={('site_id', 'date', 'item_id')},
        ),
    ]
