# Generated by Django 5.2.5 on 2025-08-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0003_alter_ismdetail_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemizedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('upc', models.CharField(blank=True, max_length=32)),
                ('image_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit_count', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('last_sold_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
