# Generated by Django 5.2.5 on 2025-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0004_itemizedinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ismdetail',
            options={'verbose_name': 'ISM Detail', 'verbose_name_plural': 'ISM Details'},
        ),
        migrations.AlterModelOptions(
            name='itemizedinventory',
            options={'verbose_name': 'Itemized Inventory', 'verbose_name_plural': 'Itemized Inventory'},
        ),
        migrations.AddField(
            model_name='itemizedinventory',
            name='site_id',
            field=models.CharField(default=62182, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemizedinventory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemizedinventory',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
